services:
  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-test:
    image: postgres:15
    container_name: my-postgres-test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"  # другой порт, чтобы не конфликтовать
    tmpfs: /var/lib/postgresql/data  # данные в памяти (не сохраняются)

  api:
    build: .
    container_name: shop_fastapi-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydb
    volumes:
      - ./:/app

volumes:
  postgres_data: